import Vehicle from "../models/vehicleModel.js";

export const seedMockVehicles = async () => {
  const mockVehicles = [
    {
      registeration_number: "KL-01-AB-1234",
      car_title: "Maruti Suzuki Swift LXI",
      car_description: "Compact hatchback suitable for city driving.",
      company: "Maruti Suzuki",
      name: "Swift",
      model: "LXI",
      year_made: 2021,
      fuel_type: "petrol",
      seats: 5,
      transmition: "manual",
      image: ["/src/Assets/booking swift lxi.jpeg"],
      price: 1500,
      base_package: "Per Day",
      with_or_without_fuel: false,
      car_type: "hatchback",
      location: "Trivandrum",
      district: "Thiruvananthapuram",
      isBooked: false,
      isAdminAdded: true,
      addedBy: "admin",
      isAdminApproved: true,
      isRejected: false
    },
    {
      registeration_number: "KL-07-CD-5678",
      car_title: "Maruti Suzuki WagonR",
      car_description: "Spacious and fuel-efficient family car.",
      company: "Maruti Suzuki",
      name: "WagonR",
      model: "VXI",
      year_made: 2020,
      fuel_type: "petrol",
      seats: 5,
      transmition: "automatic",
      image: ["/src/Assets/booking waganor blue.png"],
      price: 1800,
      base_package: "Per Day",
      with_or_without_fuel: false,
      car_type: "hatchback",
      location: "Ernakulam",
      district: "Ernakulam",
      isBooked: false,
      isAdminAdded: true,
      addedBy: "admin",
      isAdminApproved: true,
      isRejected: false
    },
    {
      registeration_number: "KL-02-EF-9012",
      car_title: "Maruti Suzuki Alto 800",
      car_description: "Affordable and reliable small car.",
      company: "Maruti Suzuki",
      name: "Alto",
      model: "LXI",
      year_made: 2019,
      fuel_type: "petrol",
      seats: 4,
      transmition: "manual",
      image: ["/src/Assets/booking-alto.png"],
      price: 1000,
      base_package: "Per Day",
      with_or_without_fuel: false,
      car_type: "hatchback",
      location: "Kollam",
      district: "Kollam",
      isBooked: false,
      isAdminAdded: true,
      addedBy: "admin",
      isAdminApproved: true,
      isRejected: false
    },
    {
      registeration_number: "KL-05-GH-3456",
      car_title: "Hyundai Creta",
      car_description: "Comfortable and powerful SUV for long trips.",
      company: "Hyundai",
      name: "Creta",
      model: "SX",
      year_made: 2022,
      fuel_type: "diesel",
      seats: 5,
      transmition: "automatic",
      image: ["/src/Assets/vehicleModel3.png"],
      price: 3500,
      base_package: "Per Day",
      with_or_without_fuel: false,
      car_type: "SUV",
      location: "Kottayam",
      district: "Kottayam",
      isBooked: false,
      isAdminAdded: true,
      addedBy: "admin",
      isAdminApproved: true,
      isRejected: false
    },
    {
      registeration_number: "KL-33-IJ-7890",
      car_title: "Maruti Suzuki Ignis",
      car_description: "Stylish compact car with premium features.",
      company: "Maruti Suzuki",
      name: "Ignis",
      model: "Zeta",
      year_made: 2021,
      fuel_type: "petrol",
      seats: 5,
      transmition: "automatic",
      image: ["/src/Assets/booking ignis.png"],
      price: 1600,
      base_package: "Per Day",
      with_or_without_fuel: false,
      car_type: "hatchback",
      location: "Thrissur",
      district: "Thrissur",
      isBooked: false,
      isAdminAdded: true,
      addedBy: "admin",
      isAdminApproved: true,
      isRejected: false
    },
    {
      registeration_number: "KL-08-KL-1122",
      car_title: "Maruti Suzuki WagonR VXI",
      car_description: "Reliable white WagonR, perfect for daily commuting.",
      company: "Maruti Suzuki",
      name: "WagonR",
      model: "LXI",
      year_made: 2018,
      fuel_type: "petrol",
      seats: 5,
      transmition: "manual",
      image: ["/src/Assets/booking waganor.png"],
      price: 1400,
      base_package: "Per Day",
      with_or_without_fuel: false,
      car_type: "hatchback",
      location: "Palakkad",
      district: "Palakkad",
      isBooked: false,
      isAdminAdded: true,
      addedBy: "admin",
      isAdminApproved: true,
      isRejected: false
    },
    {
      registeration_number: "KL-11-MN-3344",
      car_title: "Honda City",
      car_description: "Premium sedan for a luxurious experience.",
      company: "Honda",
      name: "City",
      model: "ZX",
      year_made: 2023,
      fuel_type: "petrol",
      seats: 5,
      transmition: "automatic",
      image: ["/src/Assets/vehicleModel1.png"],
      price: 4000,
      base_package: "Per Day",
      with_or_without_fuel: false,
      car_type: "sedan",
      location: "Kozhikode",
      district: "Kozhikode",
      isBooked: false,
      isAdminAdded: true,
      addedBy: "admin",
      isAdminApproved: true,
      isRejected: false
    },
    {
      registeration_number: "KL-55-OP-5566",
      car_title: "Toyota Fortuner",
      car_description: "Heavy duty premium SUV for rough terrains.",
      company: "Toyota",
      name: "Fortuner",
      model: "4x4 AT",
      year_made: 2021,
      fuel_type: "diesel",
      seats: 7,
      transmition: "automatic",
      image: ["/src/Assets/vehicleModel2.png"],
      price: 7000,
      base_package: "Per Day",
      with_or_without_fuel: false,
      car_type: "SUV",
      location: "Kannur",
      district: "Kannur",
      isBooked: false,
      isAdminAdded: true,
      addedBy: "admin",
      isAdminApproved: true,
      isRejected: false
    },
    {
      registeration_number: "KL-42-QR-7788",
      car_title: "Tata Nexon",
      car_description: "Safest compact SUV with advanced features.",
      company: "Tata",
      name: "Nexon",
      model: "XZA+",
      year_made: 2022,
      fuel_type: "hybrid",
      seats: 5,
      transmition: "automatic",
      image: ["/src/Assets/vehicleModel4.png"],
      price: 2500,
      base_package: "Per Day",
      with_or_without_fuel: false,
      car_type: "SUV",
      location: "Alappuzha",
      district: "Alappuzha",
      isBooked: false,
      isAdminAdded: true,
      addedBy: "admin",
      isAdminApproved: true,
      isRejected: false
    },
    {
      registeration_number: "KL-17-ST-9900",
      car_title: "Mahindra XUV700",
      car_description: "Feature-packed premium SUV.",
      company: "Mahindra",
      name: "XUV700",
      model: "AX7",
      year_made: 2023,
      fuel_type: "diesel",
      seats: 7,
      transmition: "automatic",
      image: ["/src/Assets/vehicleModel5.png"],
      price: 5500,
      base_package: "Per Day",
      with_or_without_fuel: false,
      car_type: "SUV",
      location: "Pathanamthitta",
      district: "Pathanamthitta",
      isBooked: false,
      isAdminAdded: true,
      addedBy: "admin",
      isAdminApproved: true,
      isRejected: false
    },
    {
      registeration_number: "KL-23-UV-1234",
      car_title: "Kia Seltos",
      car_description: "Sporty and modern compact SUV.",
      company: "Kia",
      name: "Seltos",
      model: "GTX+",
      year_made: 2021,
      fuel_type: "petrol",
      seats: 5,
      transmition: "automatic",
      image: ["/src/Assets/vehicleModel6.png"],
      price: 3200,
      base_package: "Per Day",
      with_or_without_fuel: false,
      car_type: "SUV",
      location: "Idukki",
      district: "Idukki",
      isBooked: false,
      isAdminAdded: true,
      addedBy: "admin",
      isAdminApproved: true,
      isRejected: false
    },
    {
      registeration_number: "KL-31-WX-5678",
      car_title: "Ford Endeavour",
      car_description: "Robust and powerful American SUV.",
      company: "Ford",
      name: "Endeavour",
      model: "Titanium+",
      year_made: 2020,
      fuel_type: "diesel",
      seats: 7,
      transmition: "automatic",
      image: ["/src/Assets/homepage_car_copy.jpeg"],
      price: 6500,
      base_package: "Per Day",
      with_or_without_fuel: false,
      car_type: "SUV",
      location: "Wayanad",
      district: "Wayanad",
      isBooked: false,
      isAdminAdded: true,
      addedBy: "admin",
      isAdminApproved: true,
      isRejected: false
    }
  ];

  try {
    const existingVehicle = await Vehicle.findOne({ registeration_number: "KL-01-AB-1234" });
    if (!existingVehicle) {
      await Vehicle.insertMany(mockVehicles);
      console.log(`\n✅ Successfully seeded ${mockVehicles.length} mock vehicles!\n`);
    } else {
      console.log(`\nMock vehicles already exist in DB. Skipping vehicle seeding.\n`);
    }
  } catch (error) {
    console.error("Error seeding mock vehicles:", error);
  }
};
